#
#  Release.yml
#  LocalizationExtractor
#
#  Created by mohammed souiden on 4/29/25.
#

name-template: '🚀 Release $NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: '✨ Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'

change-template: '- $TITLE (#$NUMBER)'
no-changes-template: '- No significant changes'

exclude-labels:
  - 'chore'
  - 'docs'
  - 'style'
  - 'ci'
  - 'test'
  - 'typo'

version-resolver:
  major:
    labels: ['breaking']
  minor:
    labels: ['feature', 'enhancement']
  patch:
    labels: ['fix', 'bug']

template: |
  # 🚀 Release $NEXT_PATCH_VERSION

  ## ✨ Features
  $CHANGES
