#
#  Release.yml
#  LocalizationExtractor
#
#  Created by mohammed souiden on 4/26/25.
#

name: Create GitHub Release

on:
  push:
    tags:
      - '*'

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
