#
#  Release.yml
#  LocalizationExtractor
#
#  Created by mohammed souiden on 4/26/25.
#

name: Create GitHub Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Swift 6.1
        run: |
          curl -OL https://download.swift.org/swift-6.1-release/xcode/swift-6.1-RELEASE/swift-6.1-RELEASE-osx.pkg
          sudo installer -pkg swift-6.1-RELEASE-osx.pkg -target /

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GH_KEY_LOC }}
          generate_release_notes: true
