#
#  Release.yml
#  LocalizationExtractor
#
#  Created by mohammed souiden on 4/29/25.
#

name: Draft Release

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          token: ${{ secrets.GITHUB_TOKEN }}
